---
driver:
  name: lxd
  network: lxdbr0
  wait_for_ready: true
  fix_chef_install: true
  fix_hostnamectl_bug: true

transport:
  name: lxd

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial/i386

suites:
  - name: default
    run_list:
      - jenkins2::plugins
      - jenkins2::credentials
      - jenkins2::pipelines
      - jenkins2::security
    attributes:
      plugins:
        install:
          - github
          - timestamper
      jenkins2:
        folders:
          dev:
            path: ''
          dev1:
            path: 'dev'
          dev2:
            path: 'dev/dev1'
          ops:
            path: ''
        pipelines:
          one-ci-to-rule-them-all:
            repository_url: 'git@github.com:DracoAter/one-ci-to-rule-them-all.git'
            multibranch: true
          dev-global:
            repository_url: 'test'
          ops-global:
            repository_url: 'test'
          dev1-in-dev:
            repository_url: 'test'
            path: 'dev'
          random-in-dev:
            repository_url: 'test'
            path: 'dev'
        role_strategy:
          admin:
            type: 'globalRoles'
            permissions:
              - hudson.model.Hudson.Administer
            users:
              - admin
          read:
            type: 'globalRoles'
            permissions:
              - hudson.model.Hudson.Read
              - hudson.model.Item.Discover
            users:
              - authenticated
          dev:
            type: 'projectRoles'
            permissions:
              - com.cloudbees.plugins.credentials.CredentialsProvider.View
              - hudson.model.Item.Build
              - hudson.model.Item.Cancel
              - hudson.model.Item.Discover
              - hudson.model.Item.Read
              - hudson.model.Item.Workspace
              - hudson.model.Run.Delete
              - hudson.model.Run.Update
              - hudson.scm.SCM.Tag
            pattern: 'dev(?!/dev1)/.*'
            users:
              - junior_dev
              - middle_dev
              - senior_dev
          dev1:
            type: 'projectRoles'
            permissions:
              - com.cloudbees.plugins.credentials.CredentialsProvider.View
              - hudson.model.Item.Build
              - hudson.model.Item.Cancel
              - hudson.model.Item.Discover
              - hudson.model.Item.Read
              - hudson.model.Item.Workspace
              - hudson.model.Run.Delete
              - hudson.model.Run.Update
              - hudson.scm.SCM.Tag
            pattern: 'dev/dev1(?!/dev2)/.*'
            users:
              - middle_dev
              - senior_dev
          dev2:
            type: 'projectRoles'
            permissions:
              - com.cloudbees.plugins.credentials.CredentialsProvider.View
              - hudson.model.Item.Build
              - hudson.model.Item.Cancel
              - hudson.model.Item.Discover
              - hudson.model.Item.Read
              - hudson.model.Item.Workspace
              - hudson.model.Run.Delete
              - hudson.model.Run.Update
              - hudson.scm.SCM.Tag
            pattern: 'dev/dev1/dev2/.*'
            users:
              - senior_dev
