AllCops:
  TargetRubyVersion: 2.3

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/Tab:
  Enabled: false

Layout/IndentationWidth:
  Width: 1 # 1 tab!

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/AndOr:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/Not:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/RescueModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
